services:
  php-fpm:
    image: php:8.2-fpm-alpine
    container_name: ctf-php-fpm-srv1
    restart: unless-stopped
    volumes:
      # Mount our application code
      - ./laravel:/var/www/laravel
      # Override the default php-fpm config
      - ./php-fpm/zzz-custom.conf:/usr/local/etc/php-fpm.d/zzz-custom.conf:ro
      # Mount the shared socket volume
      - ctf-socket-volume:/var/run/php-fpm
    networks:
      - ctf-app-net
      - ctf-db-net

  caddy:
    image: caddy:2-alpine
    container_name: ctf-caddy-srv1
    restart: unless-stopped
    ports:
      - "9000:80"

    volumes:
      # Mount our application code (Caddy needs access to read public/ static files)
      - ./laravel:/var/www/laravel
      # Mount Caddy configuration
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      # Mount the shared socket volume
      - ctf-socket-volume:/var/run/php-fpm
      # Mount local paths for logs and persistent data
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ../security-ips/logs:/var/log/caddy
    networks:
      - ctf-dmz-net
      - ctf-app-net

    depends_on:
      - php-fpm

volumes:
  # This shared in-memory volume will hold the Unix Domain Socket file (.sock)
  ctf-socket-volume:

networks:
  ctf-dmz-net:
    external: true

  ctf-app-net:
    external: true
  
  ctf-db-net:
    external: true
