services:
  php-fpm-2:
    image: custom-php-fpm:8.2
    container_name: php-fpm-srv2
    restart: unless-stopped
    volumes:
      - ./laravel:/var/www/laravel
      - ../server1-web/php-fpm/zzz-custom.conf:/usr/local/etc/php-fpm.d/zzz-custom.conf:ro
      - socket-volume-2:/var/run/php-fpm
    networks:
      - app-net
      - db-net

  caddy-2:
    image: caddy:2-alpine
    container_name: caddy-srv2
    restart: unless-stopped
    volumes:
      - ./laravel:/var/www/laravel
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - socket-volume-2:/var/run/php-fpm
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - dmz-net
      - app-net
    depends_on:
      - php-fpm-2

volumes:
  socket-volume-2:

networks:
  dmz-net:
    external: true
  app-net:
    external: true
  db-net:
    external: true
